import { DataProvider } from "./context/Context";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DataProvider >
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
    </DataProvider>
  );
}
